export const connectionCopy = {
  tr: {
    eyebrow: "AĞ KONTROLÜ", title: "Bağlantı merkezi", subtitle: "Bağlantını yönet. Sonucu ölç.",
    ready: "Bağlanmaya hazır.", active: "Motor çalışıyor.", unknown: "Durum alınamıyor.",
    readyHint: "Seçtiğin profil ile paket işlemeyi başlat. Erişimini aşağıdaki hedef testleriyle kontrol et.",
    activeHint: "Seçili profil devrede. Bir sitenin erişilebilir olduğunu doğrulamak için bağlantı testi çalıştır.",
    unknownHint: "Masaüstü motorundan yanıt bekleniyor. Durum doğrulandığında bağlantı kontrolü açılır.",
    start: "Bağlantıyı başlat", stop: "Motoru durdur", busy: "İşlem sürüyor…", local: "Yerel işleme", noTunnel: "VPN tüneli kullanmaz",
    profile: "Bağlantı profili", profileHint: "Ağında çalışan stratejiyi seç.", profileLocked: "Profili değiştirmek için önce motoru durdur.",
    configure: "Profilleri yönet", profileEmpty: "Profil yüklenemedi", retry: "Tekrar dene", targets: "Hedef kontrolü", targetHint: "Listendeki ilk üç hedef için TLS bağlantısını dene.",
    check: "Hedefleri test et", checking: "Test ediliyor…", unchecked: "Test edilmedi", emptyTargets: "Henüz hedef eklenmedi.", manageTargets: "Tüm hedefler",
    reachable: "TLS yanıtı alındı", blocked: "Bağlantı kurulamadı", filtered: "Filtre belirtisi", error: "Test başarısız", stale: "Önceki oturum sonucu",
    activity: "Paket etkinliği", activityHint: "İşlenen paketler / saniye", noActivity: "Henüz paket örneği yok", sampleWindow: "Son 30 örnek", paused: "Grafiği duraklat", resume: "Grafiği sürdür",
    seen: "Yakalanan", processed: "İşlenen", uptime: "Çalışma süresi", speed: "Aktarım hızı ölçülmedi", speedHint: "Paket sayısı indirme veya yükleme hızı değildir.",
    diagnostics: "Bağlantı testleri", diagnosticsHint: "Hedefleri ve profilleri karşılaştır.", repair: "Ağ onarımı", repairHint: "DNS ve bağlantı sorunlarını incele.",
    logs: "Son etkinlik", allLogs: "Günlükleri aç", noLogs: "Yeni motor olayları burada görünür.", dnsWarning: "DNS yanıtında sorun bulundu", dnsInspect: "DNS durumunu incele",
    device: "Cihazın", engine: "Anticore", destination: "Hedef", pathLabel: "Paket işleme yolu", details: "Profilin teknik adımları", loadError: "Bağlantı bilgileri yüklenemedi.",
    workspace: "ÇALIŞMA ALANI", tools: "ARAÇLAR", support: "TERCİHLER", localEngine: "Yerel motor", standby: "Beklemede", online: "Çalışıyor", unavailable: "Doğrulanamadı",
  },
  en: {
    eyebrow: "NETWORK CONTROL", title: "Connection center", subtitle: "Control your connection. Measure the result.",
    ready: "Ready to connect.", active: "Engine is running.", unknown: "Status unavailable.",
    readyHint: "Start packet processing with your selected profile. Check access using the target tests below.",
    activeHint: "Your selected profile is active. Run a connection test to verify that a site is reachable.",
    unknownHint: "Waiting for the desktop engine. Connection controls become available once status is verified.",
    start: "Start connection", stop: "Stop engine", busy: "Working…", local: "Local processing", noTunnel: "No VPN tunnel",
    profile: "Connection profile", profileHint: "Choose a strategy that works on your network.", profileLocked: "Stop the engine before changing profiles.",
    configure: "Manage profiles", profileEmpty: "Profiles unavailable", retry: "Try again", targets: "Target check", targetHint: "Test TLS connectivity to the first three listed targets.",
    check: "Test targets", checking: "Testing…", unchecked: "Not tested", emptyTargets: "No targets added yet.", manageTargets: "All targets",
    reachable: "TLS response received", blocked: "Connection failed", filtered: "Filtering detected", error: "Test failed", stale: "Previous session result",
    activity: "Packet activity", activityHint: "Processed packets / second", noActivity: "No packet samples yet", sampleWindow: "Last 30 samples", paused: "Pause chart", resume: "Resume chart",
    seen: "Captured", processed: "Processed", uptime: "Uptime", speed: "Transfer speed not measured", speedHint: "Packet counts are not download or upload speed.",
    diagnostics: "Connection tests", diagnosticsHint: "Compare targets and profiles.", repair: "Network repair", repairHint: "Inspect DNS and connection issues.",
    logs: "Recent activity", allLogs: "Open logs", noLogs: "New engine events appear here.", dnsWarning: "A problem was found in the DNS response", dnsInspect: "Inspect DNS status",
    device: "Your device", engine: "Anticore", destination: "Destination", pathLabel: "Packet processing path", details: "Profile technical steps", loadError: "Connection details could not be loaded.",
    workspace: "WORKSPACE", tools: "TOOLS", support: "PREFERENCES", localEngine: "Local engine", standby: "Standby", online: "Running", unavailable: "Unverified",
  },
};
export type ConnectionCopy = typeof connectionCopy.tr;
