export const connectionCopy = {
  tr: {
    eyebrow: "ANTICORE / AĞ OPERASYONLARI", title: "Kontrol konsolu", subtitle: "Çekirdek, trafik ve erişim denetimi.", engineControl: "PAKET İŞLEME ÇEKİRDEĞİ",
    ready: "Çekirdek beklemede.", active: "Çekirdek devrede.", unknown: "Durum alınamıyor.",
    readyHint: "Profilini seç ve çekirdeği başlat. Hedef erişimini bağlantı testleriyle doğrula.",
    activeHint: "Paket işleme etkin. Hedef erişimini aşağıdaki testlerle doğrula.",
    unknownHint: "Masaüstü çekirdeğinden yanıt bekleniyor. Durum doğrulandığında bağlantı kontrolü açılır.",
    start: "Bağlantıyı başlat", stop: "Çekirdeği durdur", busy: "İşlem sürüyor…", local: "Yerel işleme", noTunnel: "VPN tüneli kullanmaz",
    profile: "Bağlantı profili", profileHint: "Ağında çalışan stratejiyi seç.", profileLocked: "Profil kilitli. Değiştirmek için çekirdeği durdur.",
    configure: "Profilleri yönet", profileEmpty: "Profil yüklenemedi", retry: "Tekrar dene", targets: "Erişim denetimi", targetHint: "Yasaklı servisler rotasyonu · TLS bağlantı testi", cycleTargets: "Farklı hedefleri göster",
    check: "Hedefleri test et", checking: "Test ediliyor…", unchecked: "Test edilmedi", emptyTargets: "Henüz hedef eklenmedi.", manageTargets: "Tüm hedefler",
    reachable: "Erişim açık", blocked: "DPI engeli (RST)", filtered: "Zaman aşımı (Drop)", error: "Ulaşılamadı", stale: "Önceki oturum sonucu",
    activity: "Paket etkinliği", activityHint: "İşlenen paketler / saniye", noActivity: "Henüz paket örneği yok", sampleWindow: "Son 30 örnek", paused: "Grafiği duraklat", resume: "Grafiği sürdür",
    seen: "Yakalanan", processed: "İşlenen", uptime: "Çalışma süresi", speed: "Paket telemetrisi", speedHint: "Paket sayısı aktarım hızını göstermez.",
    diagnostics: "Bağlantı testleri", diagnosticsHint: "Hedefleri ve profilleri karşılaştır.", repair: "Ağ onarımı", repairHint: "DNS ve bağlantı sorunlarını incele.",
    logs: "Son etkinlik", allLogs: "Günlükleri aç", noLogs: "Yeni çekirdek olayları burada görünür.", dnsWarning: "DNS yanıtında sorun bulundu", dnsInspect: "DNS durumunu incele",
    device: "Cihazın", engine: "Anticore", destination: "Hedef", pathLabel: "Paket işleme yolu", details: "Profilin teknik adımları", loadError: "Bağlantı bilgileri yüklenemedi.",
    workspace: "ÇALIŞMA ALANI", tools: "ARAÇLAR", support: "TERCİHLER", localEngine: "Yerel çekirdek", standby: "Beklemede", online: "Çalışıyor", unavailable: "Doğrulanamadı",
  },
  en: {
    eyebrow: "ANTICORE / NETWORK OPERATIONS", title: "Control console", subtitle: "Engine, traffic and access inspection.", engineControl: "PACKET PROCESSING ENGINE",
    ready: "Engine on standby.", active: "Engine engaged.", unknown: "Status unavailable.",
    readyHint: "Select a profile and start the engine. Verify target access with connection tests.",
    activeHint: "Packet processing is active. Verify target access with the tests below.",
    unknownHint: "Waiting for the desktop engine. Connection controls become available once status is verified.",
    start: "Start connection", stop: "Stop engine", busy: "Working…", local: "Local processing", noTunnel: "No VPN tunnel",
    profile: "Connection profile", profileHint: "Choose a strategy that works on your network.", profileLocked: "Stop the engine before changing profiles.",
    configure: "Manage profiles", profileEmpty: "Profiles unavailable", retry: "Try again", targets: "Access inspection", targetHint: "Rotating blocked services · TLS connection test", cycleTargets: "Rotate targets",
    check: "Test targets", checking: "Testing…", unchecked: "Not tested", emptyTargets: "No targets added yet.", manageTargets: "All targets",
    reachable: "Access open", blocked: "DPI blocked (RST)", filtered: "Timeout (Drop)", error: "Unreachable", stale: "Previous session result",
    activity: "Packet activity", activityHint: "Processed packets / second", noActivity: "No packet samples yet", sampleWindow: "Last 30 samples", paused: "Pause chart", resume: "Resume chart",
    seen: "Captured", processed: "Processed", uptime: "Uptime", speed: "Packet telemetry", speedHint: "Packet counts do not measure transfer speed.",
    diagnostics: "Connection tests", diagnosticsHint: "Compare targets and profiles.", repair: "Network repair", repairHint: "Inspect DNS and connection issues.",
    logs: "Recent activity", allLogs: "Open logs", noLogs: "New engine events appear here.", dnsWarning: "A problem was found in the DNS response", dnsInspect: "Inspect DNS status",
    device: "Your device", engine: "Anticore", destination: "Destination", pathLabel: "Packet processing path", details: "Profile technical steps", loadError: "Connection details could not be loaded.",
    workspace: "WORKSPACE", tools: "TOOLS", support: "PREFERENCES", localEngine: "Local engine", standby: "Standby", online: "Running", unavailable: "Unverified",
  },
};
export type ConnectionCopy = typeof connectionCopy.tr;
