[package]
name = "anticore-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { version = "1", features = ["sync", "rt", "net", "io-util", "time", "macros"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
